# Generated by Django 5.0.1 on 2025-02-24 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='company',
            table='api_company',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='api_customuser',
        ),
        migrations.AlterModelTable(
            name='lead',
            table='api_lead',
        ),
        migrations.AlterModelTable(
            name='leadmessage',
            table='api_leadmessage',
        ),
    ]
