# Generated by Django 5.0.1 on 2025-02-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_company_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='funding_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
