# Generated by Django 5.0.1 on 2025-02-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_company_funding_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='funding_amount',
            field=models.BigIntegerField(default=0, help_text='Funding amount in USD'),
        ),
    ]
