# Generated by Django 5.0.1 on 2025-02-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_company_funding_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='about',
        ),
        migrations.RemoveField(
            model_name='company',
            name='contact_email',
        ),
        migrations.AlterField(
            model_name='company',
            name='funding_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.CharField(default='Unknown Company', max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name='company',
            table=None,
        ),
        migrations.AlterModelTable(
            name='customuser',
            table=None,
        ),
        migrations.AlterModelTable(
            name='lead',
            table=None,
        ),
        migrations.AlterModelTable(
            name='leadmessage',
            table=None,
        ),
    ]
