# Generated by Django 5.0.1 on 2025-02-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_company_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.CharField(default='Unknown Company', max_length=255),
        ),
    ]
