# Generated by Django 5.0.2 on 2025-02-24 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_company_about_outreach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outreach',
            name='company',
        ),
        migrations.AddField(
            model_name='outreach',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outreach_emails', to='api.lead'),
        ),
    ]
