# Generated by Django 5.0.2 on 2025-02-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_outreach_company_outreach_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreach',
            name='is_linkedin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outreach',
            name='linkedin_content',
            field=models.TextField(blank=True, help_text='LinkedIn message content'),
        ),
    ]
