# Generated by Django 5.0.2 on 2025-02-24 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_outreach_is_linkedin_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_contact_date',
            field=models.DateTimeField(blank=True, help_text='Date when the lead was last contacted', null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_score',
            field=models.IntegerField(blank=True, help_text='Lead score from 0-100', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
