# Generated by Django 5.0.2 on 2025-02-25 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_lead_last_contact_date_alter_lead_lead_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
